version: "3.9"

services:
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    image: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    restart: always
    expose:
      - "3306"
      
  nginx:
    container_name: nginx
    build: requirements/nginx
    image: nginx
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    restart: always
    ports:
      - "443:443"

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    image: wordpress
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    restart: always
    expose:
      - "9000"

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /Users/babkar/data/mariadb
      o: bind
      type: none
  wordpress:
    name: mariadb
    driver: local
    driver_opts:
      device: /Users/babkar/data/wordpress
      o: bind
      type: none

